name: happ
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - python<3.12
  - snakemake>=8.2
  - scikit-learn
  - biopython
  - tqdm
  - polars
  - pandas
  - pip
  - seqkit
  - r-ape
  - r-seqinr
  - r-data.table
  - pip:
    - snakemake-executor-plugin-slurm
    