name: happ
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - python
  - snakemake
  - scikit-learn
  - biopython
  - tqdm
  - polars
  - pandas
  - seqkit
  - r-ape
  - r-data.table
  - snakemake-executor-plugin-slurm
  - pigz
    