[project]
name = "ASV-clustering"
version = "0.1.0"
description = "Add a short description here"
authors = ["johnne <john.sundh@scilifelab.se>"]
channels = ["conda-forge", "bioconda", "main", "r", "msys2", "cduvallet"]
platforms = ["linux-64"]

[system-requirements]
linux="5.3.18"

[tasks]
init = "conda config --set channel_priority strict"
local = {cmd="snakemake --profile local", depends_on = ["init"]}
slurm = {cmd="snakemake --profile slurm", depends_on = ["init"]}
chimera_filtering = {cmd="snakemake chimera_filtering", depends_on = ["init"]}
[dependencies]
python = "3.11"
mamba = "*"
snakemake = "8.*"
scikit-learn = "1.1.3"
biopython = "1.80"
tqdm = "*"
polars = "*"
pandas = "*"
pip = "*"

[pypi-dependencies]
snakemake-executor-plugin-slurm = "*"
