use-conda: True
use-envmodules: False
use-apptainer: False
keep-going: True
printshellcmds: True
rerun-triggers: mtime
rerun-incomplete: True
local-cores: 1
jobs: 100
default-resources: "slurm_account=<your-slurm-account>"
latency-wait: 5
executor: slurm