use-conda: True
conda-frontend: "mamba"
rerun-triggers: "mtime"
keep-going: True
rerun-incomplete: True
printshellcmds: True
reason: True
restart-times: 1
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 60
