rundir: "test"
swarm:
  settings: "--fastidious"
  threads: 10
dbotu3:
  settings: ""
opticlust:
  aligner: "vsearch"
  threads: 10
lulu:
  aligner: "vsearch"
  minimum_ratio_type: "min" #Choose between 'min' and 'avg'
  minimum_ratio: 1
  minimum_match: 84
  minimum_relative_cooccurence: 0.95
vsearch:
  threads: 10
  id: .84
  iddef: 1
  query_cov: .9